openapi: 3.1.0
info:
  title: Library
  description: Library Management
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
paths:
  /library/admin/book-controller/add{id}:
    post:
      summary: add book

  /library/admin/book-controller/all-books:
    get:
      summary: get all books
      description: all books
      responses:
        '200':
          description: success

  /library/admin/book-controller/search?keyword=o:
    put:
      summary: search by name
      parameters:
        - name: keyword
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Success
        '404':
          description: book not found