#############################
#
#      BOOK-CONTROLLER
#
#############################

### Create Book
POST localhost:8080/library/admin/book-controller/add/3
Content-Type: application/json

{
  "title": "C++",
  "author": "Toshmat",
  "category": "Dasturlash"
}

### All Books
GET localhost:8080/library/admin/book-controller/all-books

### Search Book by name
GET localhost:8080/library/admin/book-controller/search?keyword=o

### Remove Book
DELETE localhost:8080/library/admin/book-controller/remove?bookId=2&userId=1



#############################
#
# STUDENT-PROFILE-CONTROLLER
#
#############################

### Add Student
POST localhost:8080/library/staff/student-profile-controller/add-student
Content-Type: application/json

{
  "fullName": "Ali Aliyev",
  "username": "alibek",
  "password": "1234567"
}

### All Students
GET localhost:8080/library/staff/student-profile-controller/all-student

### Search Student
GET localhost:8080/library/staff/student-profile-controller/search?keyword=ali

### Change Student Status
PUT localhost:8080/library/staff/student-profile-controller/status/3
Content-Type: application/json

{
  "status": "BLOCKED"
}

### Get Student Books by studentId
GET localhost:8080/library/staff/student-profile-controller/student-books/3

### Get All Student Books
GET localhost:8080/library/staff/student-profile-controller/all-student-books

### Delte profile
DELETE localhost:8080/library/staff/student-profile-controller/delete-profile/5