-- ============================================================
-- V1: Auth domeni — roles, users, sessions
-- ============================================================

CREATE TABLE roles (
                       id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(50) NOT NULL,
                       CONSTRAINT uk_roles_name UNIQUE (name)
);

-- Role.permissions -> @ElementCollection(EnumType.STRING)
CREATE TABLE role_permission (
                                 role_id    BIGINT      NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
                                 permission VARCHAR(50) NOT NULL,
                                 PRIMARY KEY (role_id, permission)
);

CREATE TABLE users (
                       id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username       VARCHAR(50)  NOT NULL,
                       password_hash  TEXT         NOT NULL,
                       full_name      VARCHAR(150) NOT NULL,
                       phone_number   VARCHAR(20),
                       status         VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                       role_id        BIGINT       NOT NULL REFERENCES roles (id),
                       last_login_at  TIMESTAMP,

    -- BaseEntity
                       created_at  TIMESTAMP    NOT NULL DEFAULT now(),
                       created_by  VARCHAR(100),
                       updated_at  TIMESTAMP,
                       updated_by  VARCHAR(100),
                       version     BIGINT       NOT NULL DEFAULT 0,
                       deleted_at  TIMESTAMP,

                       CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_role_id ON users (role_id);

-- Session.deviceInfo -> @Embedded (device_name, device_id ustunlari deb faraz qilindi)
CREATE TABLE sessions (
                          id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          user_id        BIGINT       NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                          device_name    VARCHAR(255),
                          device_id      VARCHAR(255) NOT NULL,
                          refresh_token  TEXT         NOT NULL,
                          last_used_at   TIMESTAMP    NOT NULL,
                          expires_at     TIMESTAMP    NOT NULL,
                          revoked_at     TIMESTAMP,

    -- BaseEntity
                          created_at  TIMESTAMP NOT NULL DEFAULT now(),
                          created_by  VARCHAR(100),
                          updated_at  TIMESTAMP,
                          updated_by  VARCHAR(100),
                          version     BIGINT    NOT NULL DEFAULT 0,
                          deleted_at  TIMESTAMP
);

CREATE INDEX idx_sessions_device_id_revoked_at ON sessions (device_id, revoked_at);
CREATE INDEX idx_sessions_user_id ON sessions (user_id);