-- ============================================================
-- V1: Auth domeni
-- Diqqat: Role va Session BaseEntity'dan meros OLMAYDI (sizning
-- kodingizda shunday) — shuning uchun ularda created_at/version/
-- deleted_at kabi ustunlar YO'Q, faqat User'da bor.
-- ============================================================

CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255),
    CONSTRAINT uk_role_name UNIQUE (name)
);

-- Role.permissions -> @ElementCollection(EnumType.STRING)
-- Ustun nomi "permission" — buning ishlashi uchun Role.java'dagi
-- permissions field'iga @Column(name = "permission") qo'shing,
-- aks holda Hibernate standart bo'yicha "permissions" (ko'plik)
-- nomini kutadi va ddl-auto=validate xato beradi.
CREATE TABLE role_permission
(
    role_id    BIGINT      NOT NULL REFERENCES roles (id) ON DELETE CASCADE,
    permission VARCHAR(50) NOT NULL,
    PRIMARY KEY (role_id, permission)
);

CREATE TABLE users
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL,
    password_hash TEXT         NOT NULL,
    full_name     VARCHAR(150) NOT NULL,
    phone_number  VARCHAR(20),
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    role_id       BIGINT       NOT NULL REFERENCES roles (id),
    last_login_at TIMESTAMP,

    -- BaseEntity
    created_at    TIMESTAMP    NOT NULL DEFAULT now(),
    created_by    VARCHAR(255),
    updated_at    TIMESTAMP,
    updated_by    VARCHAR(255),
    deleted_at    TIMESTAMP,
    version       BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE INDEX idx_users_role_id ON users (role_id);

-- Session.deviceInfo -> @Embedded DeviceInfo(deviceId, deviceName)
-- Hibernate standart nomlashda field nomlari shunday ustunga aylanadi:
-- deviceId -> device_id, deviceName -> device_name
CREATE TABLE sessions
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       BIGINT    NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    device_id     VARCHAR(255),
    device_name   VARCHAR(255),
    refresh_token TEXT      NOT NULL,
    last_used_at  TIMESTAMP NOT NULL,
    revoked_at    TIMESTAMP
    -- BaseEntity YO'Q — Session'da created_at/version/deleted_at ustunlari yo'q
);

CREATE INDEX idx_sessions_device_id_revoked_at ON sessions (device_id, revoked_at);
CREATE INDEX idx_sessions_user_id ON sessions (user_id);