-- ============================================================
-- V2: Kutubxona domeni
-- ============================================================

CREATE TABLE authors (
                         id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name VARCHAR(150) NOT NULL,
                         bio       TEXT,

                         created_at  TIMESTAMP NOT NULL DEFAULT now(),
                         created_by  VARCHAR(100),
                         updated_at  TIMESTAMP,
                         updated_by  VARCHAR(100),
                         version     BIGINT    NOT NULL DEFAULT 0,
                         deleted_at  TIMESTAMP
);

CREATE TABLE categories (
                            id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name VARCHAR(100) NOT NULL,

                            created_at  TIMESTAMP NOT NULL DEFAULT now(),
                            created_by  VARCHAR(100),
                            updated_at  TIMESTAMP,
                            updated_by  VARCHAR(100),
                            version     BIGINT    NOT NULL DEFAULT 0,
                            deleted_at  TIMESTAMP,

                            CONSTRAINT uk_categories_name UNIQUE (name)
);

CREATE TABLE books (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title           VARCHAR(300) NOT NULL,
                       isbn            VARCHAR(20)  NOT NULL,
                       description     TEXT,
                       published_year  INTEGER,

                       created_at  TIMESTAMP NOT NULL DEFAULT now(),
                       created_by  VARCHAR(100),
                       updated_at  TIMESTAMP,
                       updated_by  VARCHAR(100),
                       version     BIGINT    NOT NULL DEFAULT 0,
                       deleted_at  TIMESTAMP,

                       CONSTRAINT uk_books_isbn UNIQUE (isbn)
);

-- Book <-> Author (many-to-many)
CREATE TABLE book_authors (
                              book_id   BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
                              author_id BIGINT NOT NULL REFERENCES authors (id) ON DELETE CASCADE,
                              PRIMARY KEY (book_id, author_id)
);

-- Book <-> Category (many-to-many)
CREATE TABLE book_categories (
                                 book_id     BIGINT NOT NULL REFERENCES books (id) ON DELETE CASCADE,
                                 category_id BIGINT NOT NULL REFERENCES categories (id) ON DELETE CASCADE,
                                 PRIMARY KEY (book_id, category_id)
);

CREATE TABLE book_copies (
                             id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             book_id           BIGINT      NOT NULL REFERENCES books (id),
                             inventory_number  VARCHAR(50) NOT NULL,
                             status            VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',

                             created_at  TIMESTAMP NOT NULL DEFAULT now(),
                             created_by  VARCHAR(100),
                             updated_at  TIMESTAMP,
                             updated_by  VARCHAR(100),
                             version     BIGINT    NOT NULL DEFAULT 0,
                             deleted_at  TIMESTAMP,

                             CONSTRAINT uk_book_copies_inventory_number UNIQUE (inventory_number)
);

CREATE INDEX idx_book_copies_book_id ON book_copies (book_id);
CREATE INDEX idx_book_copies_book_id_status ON book_copies (book_id, status);

CREATE TABLE members (
                         id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         full_name          VARCHAR(150) NOT NULL,
                         membership_number  VARCHAR(30)  NOT NULL,
                         status             VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
                         joined_at          DATE         NOT NULL,
                         user_id            BIGINT REFERENCES users (id),

                         created_at  TIMESTAMP NOT NULL DEFAULT now(),
                         created_by  VARCHAR(100),
                         updated_at  TIMESTAMP,
                         updated_by  VARCHAR(100),
                         version     BIGINT    NOT NULL DEFAULT 0,
                         deleted_at  TIMESTAMP,

                         CONSTRAINT uk_members_membership_number UNIQUE (membership_number),
                         CONSTRAINT uk_members_user_id UNIQUE (user_id)
);

CREATE TABLE loans (
                       id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       copy_id      BIGINT      NOT NULL REFERENCES book_copies (id),
                       member_id    BIGINT      NOT NULL REFERENCES members (id),
                       borrowed_at  TIMESTAMP   NOT NULL,
                       due_date     TIMESTAMP   NOT NULL,
                       returned_at  TIMESTAMP,
                       status       VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

                       created_at  TIMESTAMP NOT NULL DEFAULT now(),
                       created_by  VARCHAR(100),
                       updated_at  TIMESTAMP,
                       updated_by  VARCHAR(100),
                       version     BIGINT    NOT NULL DEFAULT 0,
                       deleted_at  TIMESTAMP
);

CREATE INDEX idx_loans_member_id ON loans (member_id);
CREATE INDEX idx_loans_copy_id ON loans (copy_id);
-- Overdue skaner job'ining asosiy so'rovi: WHERE status = 'ACTIVE' AND due_date < now()
CREATE INDEX idx_loans_status_due_date ON loans (status, due_date);

CREATE TABLE reservations (
                              id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              book_id      BIGINT      NOT NULL REFERENCES books (id),
                              member_id    BIGINT      NOT NULL REFERENCES members (id),
                              status       VARCHAR(20) NOT NULL DEFAULT 'WAITING',
                              ready_until  TIMESTAMP,

                              created_at  TIMESTAMP NOT NULL DEFAULT now(),
                              created_by  VARCHAR(100),
                              updated_at  TIMESTAMP,
                              updated_by  VARCHAR(100),
                              version     BIGINT    NOT NULL DEFAULT 0,
                              deleted_at  TIMESTAMP
);

CREATE INDEX idx_reservations_member_id ON reservations (member_id);
-- Navbat FIFO so'rovi: WHERE book_id = ? AND status = 'WAITING' ORDER BY created_at ASC
CREATE INDEX idx_reservations_book_id_status_created_at ON reservations (book_id, status, created_at);
-- Expiry job so'rovi: WHERE status = 'READY' AND ready_until < now()
CREATE INDEX idx_reservations_status_ready_until ON reservations (status, ready_until);

CREATE TABLE fines (
                       id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       loan_id   BIGINT         NOT NULL REFERENCES loans (id),
                       member_id BIGINT         NOT NULL REFERENCES members (id),
                       amount    NUMERIC(12, 2) NOT NULL,
                       reason    VARCHAR(255)   NOT NULL,
                       status    VARCHAR(20)    NOT NULL DEFAULT 'UNPAID',

                       created_at  TIMESTAMP NOT NULL DEFAULT now(),
                       created_by  VARCHAR(100),
                       updated_at  TIMESTAMP,
                       updated_by  VARCHAR(100),
                       version     BIGINT    NOT NULL DEFAULT 0,
                       deleted_at  TIMESTAMP
);

CREATE INDEX idx_fines_member_id ON fines (member_id);
-- Overdue job'ining "shu loan uchun UNPAID fine bormi" so'rovi
CREATE INDEX idx_fines_loan_id_status ON fines (loan_id, status);